# Generated by Django 2.1.5 on 2020-05-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
    ]
